---
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - atop
      - bash-completion
      - bind9-host
      - binutils
      - bridge-utils
      - ca-certificates
      - cgroup-bin
      - command-not-found
      - cron
      - curl
      - dnsutils
      - gdb
      - gnupg-agent
      - hping3
      - htop
      - iftop
      - iotop
      - iperf3
      - iputils-arping
      - iputils-ping
      - iputils-tracepath
      - jq
      - lftp
      - libguestfs-tools
      - libvirt-clients
      - libvirt-daemon-system
      - ltrace
      - mc
      - mtr-tiny
      - net-tools
      - nload
      - nmap
      - openjdk-11-jre
      - pigz
      - pv
      - python3
      - python3-libvirt
      - python3-pip
      - python3-virtualenv
      - qemu
      - qemu-kvm
      - rsync
      - ruby
      - screen
      - smartmontools
      - software-properties-common
      - strace
      - sysstat
      - tcpdump
      - tmux
      - traceroute
      - unzip
      - vim
      - virtinst
      - vlan
      - whois
    state: present
    update_cache: yes

- name: Add user to group kvm
  user:
    name: "{{ ansible_user }}"
    groups: kvm,libvirt
    append: yes

