---
- name: install aptitude
  apt:
    name:
      - aptitude
    state: present

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - vim
      - tmux
      - htop
      - software-properties-common
      - curl
      - gnupg-agent
      - tcpdump
      - traceroute
      - dnsutils
      - net-tools
      - gdb
      - atop
      - iftop
      - iotop
      - smartmontools
      - strace
      - mc
      - python
      - python-dev
      - python-pip
      - python-virtualenv
      - python3
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - openjdk-11-jdk
      - qemu
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - binutils
      - nmap
      - cgroup-bin
      - vlan
      - jq
      - lftp
      - libguestfs-tools
      - python3-libvirt
      - virtinst
      - ruby
    state: present
    update_cache: yes

- name: Add user to group kvm
  user:
    name: "{{ ansible_user }}"
    groups: kvm,libvirt
    append: yes

